### ISSUE TITLE
How to give attributes to the root node

### ISSUE THREAD

**Issue by mathurs** [soldair/node-jsontoxml#26]
It seems neither
  var xml = jsonxml({
    name: 'sitemapindex',
    children: pageArray,
    attrs:{xmlns:'http://www.sitemaps.org/schemas/sitemap/0.9'}
  });
nor 
  var xml = jsonxml({
    'sitemapindex': pageArray,
    attrs:{xmlns:'http://www.sitemaps.org/schemas/sitemap/0.9'}
  });

seem to be able to give sitemapindex this attribute

**Comment by soldair** [comment]
i think you want to wrap it in an array like this
```
var xml = jsonxml([{
name: 'sitemapindex',
children: pageArray,
attrs:{xmlns:'http://www.sitemaps.org/schemas/sitemap/0.9'}
}]);
```
this generates 
`<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"/>`

**Comment by dsusu** [comment]
I want to just bring in a json file and assign it to a variable and compile it.like this:var jsonxml = require('jsontoxml');

var fs = require('fs');

var jsondata = fs.readFileSync('./example.js', 'utf8')

console.log(jsondata)

var xml = jsonxml({
  xml: jsondata
})
console.log(xml)

**Comment by jlguenego** [comment]
I need to convert the following json into xml:
```
{
    "content": [
        {
            "_id": "012345678901234567890123",
            "lastname": "Guénégo",
            "firstname": "Jean-Louis"
        },
        {
            "_id": "5ae5ef542523d439d8083335",
            "lastname": "Phengsiaroun",
            "firstname": "Dany",
            "__v": 0
        }
    ]
}
```

The output does not satisfy because it does not clearly sepearate the array items:
```
<content>
    <_id>012345678901234567890123</_id>
    <lastname>Guénégo</lastname>
    <firstname>Jean-Louis</firstname>
    <_id>5ae5ef542523d439d8083335</_id>
    <lastname>Phengsiaroun</lastname>
    <firstname>Dany</firstname>
    <__v>0</__v>
</content>
```

I would suggest to add in the options something like:
handleArrayElement: true

that would produce:

```
<content>
    <item>
        <_id>012345678901234567890123</_id>
        <lastname>Guénégo</lastname>
        <firstname>Jean-Louis</firstname>
    </item>
    <item>
        <_id>5ae5ef542523d439d8083335</_id>
        <lastname>Phengsiaroun</lastname>
        <firstname>Dany</firstname>
        <__v>0</__v>
    <item>
</content>
```

**Comment by Kaliph** [comment]
Hello I want to do the same. But unfortunately I do not understand how it works yet.

`let value1 = "testname";
let value2 = "2.10.5";
let live_event = { "live_event": {}
};

let liveeventvalues = jsonxml(live_event, { xmlHeader: true });`

The output should be like this

<live_event value1="testname" value2="2.10.5">
</live_event>

live_event is my root element. How can I add those custom values to it?
Can I add them over the available options?

Any help would be appreaciated. Thankyou!

**Comment by luky1984** [comment]
> var xml = jsonxml([{
> name: 'sitemapindex',
> children: pageArray,
> attrs:{xmlns:'http://www.sitemaps.org/schemas/sitemap/0.9'}
> }]);

hi your code generates this not what you say..

`<name>sitemapindex</name><attrs><xmlns>http://www.sitemaps.org/schemas/sitemap/0.9</xmlns></attrs>`

**Comment by soldair** [comment]
I just tested it it certainly generates what i said.
```
let j = require('jsontoxml')
console.log(j([{
name: 'sitemapindex',
children: [],
attrs:{xmlns:'http://www.sitemaps.org/schemas/sitemap/0.9'}
}]))
```
```
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"/>
```

i believe you forgot to wrap the argument with an array. try this.
```
const jsontoxml = require('jsontoxml');
let page = [
{
name: 'sitemapindex',
children: [],
attrs:{xmlns:'http://www.sitemaps.org/schemas/sitemap/0.9'}
}
]

console.log(jsontoxml(page))
```
