### ISSUE TITLE
The browser project is introduced, and there are errors in the ES6 environment.

### ISSUE THREAD

**Issue by xiaofan9** [soldair/node-jsontoxml#33]
In the es6 environment, this is undefined
![image](https://user-images.githubusercontent.com/16103130/46254253-d5869f00-c4be-11e8-9c55-7f077bfcac5e.png)
![image](https://user-images.githubusercontent.com/16103130/46254211-3d88b580-c4be-11e8-9fca-339c630bf902.png)

**Comment by soldair** [comment]
published to npm as version 1.0.1

**Comment by xiaofan9** [comment]
@soldair I'm sorry, after some genius reply, because of the National Day holiday in China.

The reason for this problem is indeed the strict mode of changing the Babel configuration as follows [can be reproduced]：

![image](https://user-images.githubusercontent.com/16103130/46594977-b1ebd600-cb08-11e8-969e-44d28f112515.png)
