### ISSUE TITLE
How to set in JSON tag with dash("-") ?

### ISSUE THREAD

**Issue by AndrewKuktenko** [soldair/node-jsontoxml#34]
I have to get this format XML.
`<batch-order xmlns="http://ws.plimus.com">
      <shopper>
      <web-info>
      <ip>62.219.121.253</ip>
    <remote-host>www.merchant.com</remote-host>....`
Problem is in tag names with dash. I cannot pass it in JSON, because it is not valid.

Thank you!

**Comment by soldair** [comment]
i think you just wrap it in quotes. - is certainly allowed as a key value by json
```js
let jsontoxml = require('jsontoxml')
console.log(jsontoxml({"-":'hi'}))
```
