### ISSUE TITLE
Xml conversion not working for more rows.

### ISSUE THREAD

**Issue by shreev1** [soldair/node-jsontoxml#35]
I tried for 90 records, it worked but for 350, it's not showing proper xml while json is correct only.
Please help urgently on this.

**Comment by soldair** [comment]
not sure why it would be different. there is not logic to do that.
in order to point you in the right direction i'd need a working example

**Comment by shreev1** [comment]
May be issue happened in Saving. I have stored the data in a variable and then want to download it in XML file format on click on a link. 

I m new to react, please guide me, may be in using wrong method causing this issue.

**Comment by shreev1** [comment]
I'm using save-file package, it's doing its work correctly but when I save the XML file using this for 370 records having attributes 23 each, it's not generated in proper format of XML but in one line
Please guide me

**Comment by shreev1** [comment]
Issue was & in the data
